# Generated by Django 2.1.7 on 2019-02-26 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=None, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.CharField(default=' ', max_length=100)),
                ('city', models.CharField(default='', max_length=20)),
                ('phone', models.IntegerField(default=0)),
                ('head_shot', models.ImageField(blank=True, upload_to='profil_images/admin')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('department_id', models.CharField(default=' ', max_length=50)),
                ('course_name', models.CharField(default='', max_length=50)),
                ('semester', models.CharField(default=' ', max_length=50)),
                ('year', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('faculty_id', models.CharField(default='', max_length=20)),
                ('department_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LecturerData',
            fields=[
                ('l_id', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default=' ', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default=' ', max_length=500)),
                ('phone', models.IntegerField(default=0)),
                ('country', models.CharField(default=' ', max_length=50)),
                ('address', models.CharField(default=' ', max_length=100)),
                ('faculty', models.CharField(default='', max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='profil_images/lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsData',
            fields=[
                ('reg_no', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default=' ', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default=' ', max_length=500)),
                ('phone', models.IntegerField(default=0)),
                ('country', models.CharField(default=' ', max_length=50)),
                ('address', models.CharField(default=' ', max_length=100)),
                ('department', models.CharField(default='', max_length=200)),
                ('year', models.CharField(default=' ', max_length=5)),
                ('picture', models.ImageField(blank=True, upload_to='profil_images/students')),
            ],
        ),
    ]
