# Generated by Django 2.1.7 on 2019-04-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('a_id', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('stu_id', models.CharField(default=' ', max_length=50)),
                ('class_id', models.CharField(default='', max_length=50)),
                ('semester', models.CharField(default=' ', max_length=50)),
                ('year', models.CharField(default=' ', max_length=50)),
                ('attendance', models.CharField(default=' ', max_length=50)),
            ],
        ),
    ]
