# Generated by Django 2.1.7 on 2019-05-06 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190411_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturerattendance',
            name='date',
        ),
        migrations.AddField(
            model_name='lecturerattendance',
            name='day',
            field=models.CharField(blank=True, default=datetime.datetime.now, max_length=100),
        ),
        migrations.AddField(
            model_name='lecturerattendance',
            name='recogtime',
            field=models.CharField(blank=True, default=datetime.datetime.now, max_length=100),
        ),
    ]
