# Generated by Django 2.1.7 on 2019-05-07 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190506_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturerattendance',
            old_name='recogtime',
            new_name='time_in',
        ),
        migrations.AddField(
            model_name='lecturerattendance',
            name='time_out',
            field=models.CharField(blank=True, default=datetime.datetime.now, max_length=100),
        ),
    ]
