# Generated by Django 2.1.7 on 2019-05-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190507_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('timeframe', models.CharField(default='120', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentsdata',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentsdata',
            name='year',
        ),
    ]
