# Generated by Django 2.1.7 on 2019-05-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190509_1034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Time',
            new_name='Time_frame',
        ),
    ]
